### PR TITLE
add USB mass storage support & disks clean-up

### PR DESCRIPTION
**Pull request by sneakywumpus**
You can now mount the SD card on the host with the 'u' command from the config menu. Only tested on Linux. Won't win any speed prices, but totally usable for copying IBM 8-inch floppy disk images.

Clean-up LCD driver comments.

Make local copy of pico_stdio_usb, rename it to stdio_msc_usb, and use it.

Rename all PICO_STDIO_USB symbols to STDIO_MSC_USB. Explicitly link tinyusb_device library and remove all LIB_TINYUSB_HOST and LIB_TINYUSB_DEVICE conditionals from stdio_msc_usb.

Add USB mass storage code based on pico-sdk/lib/tinyusb/examples/device/cdc_msc. Only thing I needed to add was adding SCSI_CMD_PREVENT_ALLOW_MEDIUM_REMOVAL handling to allow "Eject" to work (at least on Linux).
    
Since this adds a new interface to the USB descriptor I needed to change the VID/PID. I used the test device 1209/0001 from https://pid.codes .

Or we could buy an official USB vendor ID for $6000...

### CODE REVIEW

**Comment by sneakywumpus** [comment]
I use picotool to control/flash my RP2040-GEEK. To allow it work with the new VID/PID I made the following changes:

```
diff --git a/picoboot_connection/picoboot_connection.c b/picoboot_connection/picoboot_connection.c
index d1f2bee..0818a55 100644
--- a/picoboot_connection/picoboot_connection.c
+++ b/picoboot_connection/picoboot_connection.c
@@ -26,6 +26,9 @@ static bool verbose;
 #define PRODUCT_ID_MICROPYTHON 0x0005u
 #define PRODUCT_ID_STDIO_USB   0x000au
 
+#define VENDOR_ID_PID_CODES    0x1209u
+#define PRODUCT_ID_TEST_PID    0x0001u
+
 uint32_t crc32_for_byte(uint32_t remainder) {
     const uint32_t POLYNOMIAL = 0x4C11DB7;
     remainder <<= 24u;
@@ -65,21 +68,29 @@ enum picoboot_device_result picoboot_open_device(libusb_device *device, libusb_d
         output("Failed to read device descriptor");
     }
     if (!ret) {
-        if (desc.idVendor != VENDOR_ID_RASPBERRY_PI) {
+        if (desc.idVendor == VENDOR_ID_RASPBERRY_PI) {
+            switch (desc.idProduct) {
+                case PRODUCT_ID_MICROPYTHON:
+                    return dr_vidpid_micropython;
+                case PRODUCT_ID_PICOPROBE:
+                    return dr_vidpid_picoprobe;
+                case PRODUCT_ID_STDIO_USB:
+                    return dr_vidpid_stdio_usb;
+                case PRODUCT_ID_RP2_USBBOOT:
+                    break;
+                default:
+                    return dr_vidpid_unknown;
+            }
+        } else if (desc.idVendor == VENDOR_ID_PID_CODES) {
+            switch (desc.idProduct) {
+                case PRODUCT_ID_TEST_PID:
+                    return dr_vidpid_stdio_usb;
+                default:
+                    return dr_vidpid_unknown;
+            }
+        } else {
             return dr_vidpid_unknown;
         }
-        switch (desc.idProduct) {
-            case PRODUCT_ID_MICROPYTHON:
-                return dr_vidpid_micropython;
-            case PRODUCT_ID_PICOPROBE:
-                return dr_vidpid_picoprobe;
-            case PRODUCT_ID_STDIO_USB:
-                return dr_vidpid_stdio_usb;
-            case PRODUCT_ID_RP2_USBBOOT:
-                break;
-            default:
-                return dr_vidpid_unknown;
-        }
         ret = libusb_get_active_config_descriptor(device, &config);
         if (ret && verbose) {
             output("Failed to read config descriptor\n");
@@ -425,4 +436,4 @@ int picoboot_peek(libusb_device_handle *usb_device, uint32_t addr, uint32_t *dat
         return ret;
     return picoboot_read(usb_device, PEEK_POKE_CODE_LOC + picoboot_peek_cmd_len, (uint8_t *) data, sizeof(uint32_t));
 }
-#endif
\ No newline at end of file
+#endif
```

**Comment by sneakywumpus** [comment]
Did a bit of clean-up: split-off disks stuff into new files disks.[hc], config menu code

**Comment by udo-munk** [comment]
If you connect it to a Windows system now, the USB device will not be recognized anymore, and Windows 11 crashes after a few minutes of trying.

**Comment by udo-munk** [comment]
Works on OSX 10.9.5.

**Comment by sneakywumpus** [comment]
Did you ever have any other USB devices with VID/PID 1209/0001 connected? I have read, that Windows is extremely picky about this, you need to uninstall any drivers for other devices using this VID/PID.

**Comment by sneakywumpus** [comment]
Does it work on your new MacBook?

**Comment by udo-munk** [comment]
Yes, also works OK with MacOS 14.5.

No, never had a device connected with this VID/PID. Windows complains that it has no driver for this, but keeps trying to connect, the wait terminal text is blinking. Went into device manager to see what's up with the device, but it doesn't show at all. And then Windows crashed.

**Comment by udo-munk** [comment]
Use the official Raspberry VID/PID for the device I guess.

**Comment by udo-munk** [comment]
Tried with the official Raspberry VID/PID for the cdc uart, but Windows still will not recognize the device at all. At least it won't crash anymore. Something is wrong with this MSC USB code.

**Comment by sneakywumpus** [comment]
I just finished updating and backing up my Windows 11 VM (didn't use it since January), and connected the Geek to it. No crashes. Device manager show a Communications Port, Disk Drive and unknown "Reset" device.
Typed "u" in putty and the Explorer showed the disk. Ejected it, and menu continues. Pressed "u" again, Explorer windows pops up...

**Comment by sneakywumpus** [comment]
image

**Comment by sneakywumpus** [comment]
Then I re-flashed the Geek without the mass storage code, attached it, worked. Re-flashed again with the mass storage code, attached it and BOOM! Endless device reset loop in Windows.

Lots of DeviceSetupManager id 131 errors in the Event Viewer. Goggled it. Seems like a known problem.

https://answers.microsoft.com/en-us/windows/forum/all/metadata-staging-failed-result0x80070490-for/73130c25-0414-4925-8368-ee42c731d554

https://answers.microsoft.com/en-us/windows/forum/all/device-setup-manager-metadata-staging-failed-event/67212749-06b1-48c6-9033-f560badb8751

Windows tries to download some stuff and fails because of a wrong URL.

One temporary fix is to disable the automatic driver downloads in Settings -> System -> About -> Advanced system settings -> Hardware -> Device installation settings and disable the downloads.

Can you try this and re-flash your GEEK with the mass sttorage firmware and attach to the Windows machine?

**Comment by udo-munk** [comment]
I have that disabled already because some Ham USB prgramming adapter also won't work with a newer updated driver.

**Comment by sneakywumpus** [comment]
Hmm. The mass storage code worked again in my VM after I set that setting to "no".

**Comment by udo-munk** [comment]
Tried again, it runs in a constant reboot loop.

**Comment by sneakywumpus** [comment]
Can you add "STDIO_MSC_USB_ENABLE_RESET_VIA_VENDOR_INTERFACE=0" after "LCD_REFRESH=30" and test that. This will disable the "Reset" interface, for which Windows doesn't have a driver.

**Comment by udo-munk** [comment]
Doesn't help, still fast reboots and no device at all.

**Comment by sneakywumpus** [comment]
I'm running out of ideas... I hate Windows... Do you have the "DEVMGR_SHOW_NONPRESENT_DEVICES" environment variable set? And then "show all devices" in device manager and uninstall (including drivers) any unused devices and the Pico and the MSC Geek and try again.

**Comment by udo-munk** [comment]
No I don't have that set, it shown only the current connected devices. Also I don't want that, because it is difficult enough already ;-)
Uninstalling drivers with disabled drivers download, no idea where to get all the used drivers then again to install manually. Probably days of work to get everything working again :-(

**Pull request merged**
